# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-18 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20181017_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='avatars/default.png', upload_to='avatars/', verbose_name='头像'),
        ),
    ]
