# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-21 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_remove_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='create_time',
        ),
    ]
