# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-23 13:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_auto_20181022_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Detail'),
        ),
    ]
