# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-03 21:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0025_auto_20181103_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='down',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
