# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-04 15:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0029_auto_20181104_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='updown',
            name='article',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='updown',
            name='updown',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='updown',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
